spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/waitingList
    username: mohammed
    password: superman
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080